from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
QRadialGradient,QCursor)
from PySide2.QtWidgets import *
from PySide2 import QtCore,QtWidgets,QtGui
        
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1080, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1080, 720))
        MainWindow.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Top_Bar = QtWidgets.QFrame(self.centralwidget)
        self.Top_Bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Top_Bar.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.Top_Bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Top_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top_Bar.setObjectName("Top_Bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Top_Bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_toggle = QtWidgets.QFrame(self.Top_Bar)
        self.frame_toggle.setMaximumSize(QtCore.QSize(70, 40))
        self.frame_toggle.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.frame_toggle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toggle.setObjectName("frame_toggle")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_toggle)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Btn_Toggle = QtWidgets.QPushButton(self.frame_toggle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_Toggle.sizePolicy().hasHeightForWidth())
        self.Btn_Toggle.setSizePolicy(sizePolicy)
        self.Btn_Toggle.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px solid;")
        self.Btn_Toggle.setObjectName("Btn_Toggle")
        self.Btn_Toggle.setIcon(QIcon('Images/cil-list.png'))
        self.verticalLayout_2.addWidget(self.Btn_Toggle)
        self.horizontalLayout.addWidget(self.frame_toggle)
        self.frame_top = QtWidgets.QFrame(self.Top_Bar)
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout.addWidget(self.frame_top)
        self.verticalLayout.addWidget(self.Top_Bar)
        self.Content = QtWidgets.QFrame(self.centralwidget)
        self.Content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.Content)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_page_1 = QtWidgets.QPushButton(self.frame_left_menu)
        self.btn_page_1.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_1.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_page_1.setObjectName("btn_page_1")
        self.btn_page_1.setEnabled(False)
        self.verticalLayout_3.addWidget(self.btn_page_1)
        self.btn_page_2 = QtWidgets.QPushButton(self.frame_left_menu)
        self.btn_page_2.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_2.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_page_2.setObjectName("btn_page_2")
        self.btn_page_2.setEnabled(False)
        self.verticalLayout_3.addWidget(self.btn_page_2)
        self.btn_page_3 = QtWidgets.QPushButton(self.frame_left_menu)
        self.btn_page_3.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_3.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_page_3.setObjectName("btn_page_3")
        self.btn_page_3.setEnabled(False)
        self.verticalLayout_3.addWidget(self.btn_page_3)
        self.frame_top_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_top_menus.setEnabled(True)
        self.frame_top_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menus.setObjectName("frame_top_menus")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_21 = QtWidgets.QFrame(self.frame_top_menus)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")

        self.verticalLayout_4_1 = QtWidgets.QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_4_1.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4_1.setSpacing(0)
        self.verticalLayout_4_1.setObjectName("verticalLayout_4_1")
        self.btn_page_4 = QtWidgets.QPushButton(self.frame_21)
        self.btn_page_4.setGeometry(QtCore.QRect(0, 479, 68, 61))
        self.btn_page_4.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_4.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_page_4.setObjectName("btn_page_4")
        self.btn_page_4.setEnabled(False)
        self.verticalLayout_4_1.addWidget(self.btn_page_4)
        self.verticalLayout_4.addWidget(self.frame_21)
        self.verticalLayout_3.addWidget(self.frame_top_menus)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_pages = QtWidgets.QFrame(self.Content)
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_pages)
        self.stackedWidget.setObjectName("stackedWidget")
        self.home_page = QtWidgets.QWidget()
        self.home_page.setObjectName("home_page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.home_page)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame = QtWidgets.QFrame(self.home_page)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 0, 951, 361))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Images/corona-page-og.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(60, 410, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setToolTip("")
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setTextFormat(QtCore.Qt.RichText)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(70, 450, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(290, 410, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setToolTip("")
        self.label_6.setAutoFillBackground(False)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setTextFormat(QtCore.Qt.RichText)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(300, 450, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(60, 510, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setToolTip("")
        self.label_8.setAutoFillBackground(False)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setTextFormat(QtCore.Qt.RichText)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(70, 550, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.Live_cases_button = QtWidgets.QPushButton(self.frame)
        self.Live_cases_button.setGeometry(QtCore.QRect(290, 540, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Live_cases_button.setFont(font)
        self.Live_cases_button.setAutoFillBackground(False)
        self.Live_cases_button.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"")
        self.Live_cases_button.setObjectName("Live_cases_button")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(550, 400, 371, 211))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.News_labl_1 = QtWidgets.QLabel(self.frame_2)
        self.News_labl_1.setGeometry(QtCore.QRect(20, 10, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.News_labl_1.setFont(font)
        self.News_labl_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.News_labl_1.setObjectName("News_labl_1")
        self.News_label_2 = QtWidgets.QLabel(self.frame_2)
        self.News_label_2.setGeometry(QtCore.QRect(20, 50, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.News_label_2.setFont(font)
        self.News_label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.News_label_2.setObjectName("News_label_2")
        self.News_label_3 = QtWidgets.QLabel(self.frame_2)
        self.News_label_3.setGeometry(QtCore.QRect(20, 90, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.News_label_3.setFont(font)
        self.News_label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.News_label_3.setObjectName("News_label_3")
        self.More_news_button = QtWidgets.QPushButton(self.frame_2)
        self.More_news_button.setGeometry(QtCore.QRect(220, 140, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.More_news_button.setFont(font)
        self.More_news_button.setAutoFillBackground(False)
        self.More_news_button.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"")
        self.More_news_button.setObjectName("More_news_button")
        self.verticalLayout_7.addWidget(self.frame)
        self.stackedWidget.addWidget(self.home_page)
        self.analysis_page = QtWidgets.QWidget()
        self.analysis_page.setObjectName("analysis_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.analysis_page)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_3 = QtWidgets.QFrame(self.analysis_page)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.widget = QtWidgets.QWidget(self.frame_3)
        self.widget.setGeometry(QtCore.QRect(10, 20, 881, 81))
        self.widget.setObjectName("widget")
        self.frame_4 = QtWidgets.QFrame(self.widget)
        self.frame_4.setGeometry(QtCore.QRect(-11, 0, 931, 71))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(14, 0, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.state_radio_button = QtWidgets.QRadioButton(self.frame_4)
        self.state_radio_button.setGeometry(QtCore.QRect(20, 40, 95, 20))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.state_radio_button.setFont(font)
        self.state_radio_button.setStyleSheet("color: rgb(255, 255, 255);")
        self.state_radio_button.setObjectName("state_radio_button")
        self.state_radio_button.setChecked(True)
        self.gender_radio_button = QtWidgets.QRadioButton(self.frame_4)
        self.gender_radio_button.setGeometry(QtCore.QRect(150, 40, 95, 20))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.gender_radio_button.setFont(font)
        self.gender_radio_button.setStyleSheet("color: rgb(255, 255, 255);")
        self.gender_radio_button.setObjectName("gender_radio_button")
        self.cases_button = QtWidgets.QRadioButton(self.frame_4)
        self.cases_button.setGeometry(QtCore.QRect(290, 40, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.cases_button.setFont(font)
        self.cases_button.setStyleSheet("color: rgb(255, 255, 255);")
        self.cases_button.setObjectName("cases_button")
        self.death_radio_button = QtWidgets.QRadioButton(self.frame_4)
        self.death_radio_button.setGeometry(QtCore.QRect(420, 40, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.death_radio_button.setFont(font)
        self.death_radio_button.setStyleSheet("color: rgb(255, 255, 255);")
        self.death_radio_button.setObjectName("death_radio_button")
        self.recovery_radio_button = QtWidgets.QRadioButton(self.frame_4)
        self.recovery_radio_button.setGeometry(QtCore.QRect(580, 40, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.recovery_radio_button.setFont(font)
        self.recovery_radio_button.setStyleSheet("color: rgb(255, 255, 255);")
        self.recovery_radio_button.setObjectName("recovery_radio_button")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_3)
        self.stackedWidget_2.setGeometry(QtCore.QRect(9, 109, 961, 521))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.Select_state_button = QtWidgets.QPushButton(self.page_7)
        self.Select_state_button.setGeometry(QtCore.QRect(50, 20, 421, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.Select_state_button.setFont(font)
        self.Select_state_button.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 255);")
        self.Select_state_button.setObjectName("Select_state_button")
        self.Other_state_button = QtWidgets.QPushButton(self.page_7)
        self.Other_state_button.setGeometry(QtCore.QRect(470, 20, 421, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.Other_state_button.setFont(font)
        self.Other_state_button.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.Other_state_button.setObjectName("Other_state_button")
        self.stackedWidget_3 = QtWidgets.QStackedWidget(self.page_7)
        self.stackedWidget_3.setGeometry(QtCore.QRect(59, 69, 831, 461))
        self.stackedWidget_3.setObjectName("stackedWidget_3")
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.Select_state_pic = QtWidgets.QLabel(self.page_9)
        self.Select_state_pic.setGeometry(QtCore.QRect(180, -40, 431, 521))
        self.Select_state_pic.setText("")
        self.Select_state_pic.setPixmap(QtGui.QPixmap("Images/Focus map.png"))
        self.Select_state_pic.setScaledContents(True)
        self.Select_state_pic.setObjectName("Select_state_pic")
        self.rajasthan = QtWidgets.QRadioButton(self.page_9)
        self.rajasthan.setGeometry(QtCore.QRect(250, 160, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.rajasthan.setFont(font)
        self.rajasthan.setStyleSheet("color: rgb(255, 255, 255);")
        self.rajasthan.setObjectName("rajasthan")
        self.maharashtra = QtWidgets.QRadioButton(self.page_9)
        self.maharashtra.setGeometry(QtCore.QRect(290, 260, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.maharashtra.setFont(font)
        self.maharashtra.setStyleSheet("color: rgb(255, 255, 255);")
        self.maharashtra.setObjectName("maharashtra")
        self.madhyapradesh = QtWidgets.QRadioButton(self.page_9)
        self.madhyapradesh.setGeometry(QtCore.QRect(330, 210, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.madhyapradesh.setFont(font)
        self.madhyapradesh.setStyleSheet("color: rgb(255, 255, 255);")
        self.madhyapradesh.setObjectName("madhyapradesh")
        self.tamil_nadu = QtWidgets.QRadioButton(self.page_9)
        self.tamil_nadu.setGeometry(QtCore.QRect(340, 390, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.tamil_nadu.setFont(font)
        self.tamil_nadu.setStyleSheet("color: rgb(255, 255, 255);")
        self.tamil_nadu.setObjectName("tamil_nadu")
        self.Uttar_Pradesh = QtWidgets.QRadioButton(self.page_9)
        self.Uttar_Pradesh.setGeometry(QtCore.QRect(390, 160, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.Uttar_Pradesh.setFont(font)
        self.Uttar_Pradesh.setStyleSheet("color: rgb(255, 255, 255);")
        self.Uttar_Pradesh.setObjectName("Uttar_Pradesh")
        self.punjab = QtWidgets.QRadioButton(self.page_9)
        self.punjab.setGeometry(QtCore.QRect(300, 90, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.punjab.setFont(font)
        self.punjab.setStyleSheet("color: rgb(255, 255, 255);")
        self.punjab.setObjectName("punjab")
        self.delhi = QtWidgets.QRadioButton(self.page_9)
        self.delhi.setGeometry(QtCore.QRect(330, 120, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.delhi.setFont(font)
        self.delhi.setStyleSheet("color: rgb(255, 255, 255);")
        self.delhi.setObjectName("delhi")
        self.Analyse_button = QtWidgets.QPushButton(self.page_9)
        self.Analyse_button.setGeometry(QtCore.QRect(662, 390, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.Analyse_button.setFont(font)
        self.Analyse_button.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.Analyse_button.setObjectName("Analyse_button")
        self.Go_online_button = QtWidgets.QPushButton(self.page_9)
        self.Go_online_button.setGeometry(QtCore.QRect(660, 320, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.Go_online_button.setFont(font)
        self.Go_online_button.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.Go_online_button.setObjectName("Go_online_button")
        self.stackedWidget_3.addWidget(self.page_9)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.Select_state_pic_2 = QtWidgets.QLabel(self.page_10)
        self.Select_state_pic_2.setGeometry(QtCore.QRect(180, -40, 431, 521))
        self.Select_state_pic_2.setText("")
        self.Select_state_pic_2.setPixmap(QtGui.QPixmap("Images/Other_states.png"))
        self.Select_state_pic_2.setScaledContents(True)
        self.Select_state_pic_2.setObjectName("Select_state_pic_2")
        self._Other_state_analyse_button = QtWidgets.QPushButton(self.page_10)
        self._Other_state_analyse_button.setGeometry(QtCore.QRect(660, 390, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self._Other_state_analyse_button.setFont(font)
        self._Other_state_analyse_button.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self._Other_state_analyse_button.setObjectName("_Other_state_analyse_button")
        self.Go_onlline_button = QtWidgets.QPushButton(self.page_10)
        self.Go_onlline_button.setGeometry(QtCore.QRect(660, 320, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.Go_onlline_button.setFont(font)
        self.Go_onlline_button.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.Go_onlline_button.setObjectName("Go_onlline_button")
        self.stackedWidget_3.addWidget(self.page_10)
        self.stackedWidget_2.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.label_13 = QtWidgets.QLabel(self.page_8)
        self.label_13.setGeometry(QtCore.QRect(0, -10, 931, 101))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setAutoFillBackground(False)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.page_8)
        self.label_14.setGeometry(QtCore.QRect(50, 90, 821, 351))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("Images/covid_map.jpg"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.Analyse_button__death_3 = QtWidgets.QPushButton(self.page_8)
        self.Analyse_button__death_3.setGeometry(QtCore.QRect(800, 450, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.Analyse_button__death_3.setFont(font)
        self.Analyse_button__death_3.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.Analyse_button__death_3.setObjectName("Analyse_button__death_3")
        self.Analyse_button_4 = QtWidgets.QPushButton(self.page_8)
        self.Analyse_button_4.setGeometry(QtCore.QRect(0, 450, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.Analyse_button_4.setFont(font)
        self.Analyse_button_4.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.Analyse_button_4.setObjectName("Analyse_button_4")
        self.stackedWidget_2.addWidget(self.page_8)
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setObjectName("page_11")
        self.label_15 = QtWidgets.QLabel(self.page_11)
        self.label_15.setGeometry(QtCore.QRect(20, 30, 861, 91))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.listWidget_case = QtWidgets.QListWidget(self.page_11)
        self.listWidget_case.setGeometry(QtCore.QRect(185, 170, 531, 111))
        self.listWidget_case.setObjectName("listWidget_case")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.listWidget_case.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.listWidget_case.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.listWidget_case.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.listWidget_case.addItem(item)
        self.list_case_label = QtWidgets.QLabel(self.page_11)
        self.list_case_label.setGeometry(QtCore.QRect(190, 340, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.list_case_label.setFont(font)
        self.list_case_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.list_case_label.setObjectName("list_case_label")
        self._analyse_case_button = QtWidgets.QPushButton(self.page_11)
        self._analyse_case_button.setGeometry(QtCore.QRect(580, 330, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self._analyse_case_button.setFont(font)
        self._analyse_case_button.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self._analyse_case_button.setObjectName("_analyse_case_button")
        self.stackedWidget_2.addWidget(self.page_11)
        self.page_12 = QtWidgets.QWidget()
        self.page_12.setObjectName("page_12")
        self.label_17 = QtWidgets.QLabel(self.page_12)
        self.label_17.setGeometry(QtCore.QRect(4, 20, 911, 91))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName("label_17")
        self.death_list = QtWidgets.QListWidget(self.page_12)
        self.death_list.setGeometry(QtCore.QRect(180, 170, 531, 111))
        self.death_list.setObjectName("death_list")
        self.death_list.setEnabled(False)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.death_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.death_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.death_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.death_list.addItem(item)
        self.selected_label = QtWidgets.QLabel(self.page_12)
        self.selected_label.setGeometry(QtCore.QRect(190, 330, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.selected_label.setFont(font)
        self.selected_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.selected_label.setObjectName("selected_label")
        self.Analyse_button__death = QtWidgets.QPushButton(self.page_12)
        self.Analyse_button__death.setGeometry(QtCore.QRect(570, 320, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.Analyse_button__death.setFont(font)
        self.Analyse_button__death.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.Analyse_button__death.setObjectName("Analyse_button__death")
        self.label_20 = QtWidgets.QLabel(self.page_12)
        self.label_20.setGeometry(QtCore.QRect(370, 410, 91, 71))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("Images/heart_beat.png"))
        self.label_20.setScaledContents(False)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.page_12)
        self.label_21.setGeometry(QtCore.QRect(280, 410, 91, 71))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("Images/heart_beat.png"))
        self.label_21.setScaledContents(False)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.page_12)
        self.label_22.setGeometry(QtCore.QRect(190, 410, 91, 71))
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("Images/heart_beat.png"))
        self.label_22.setScaledContents(False)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.page_12)
        self.label_23.setGeometry(QtCore.QRect(100, 410, 91, 71))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("Images/heart_beat.png"))
        self.label_23.setScaledContents(False)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.page_12)
        self.label_24.setGeometry(QtCore.QRect(10, 410, 91, 71))
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap("Images/heart_beat.png"))
        self.label_24.setScaledContents(False)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.page_12)
        self.label_25.setGeometry(QtCore.QRect(460, 410, 91, 71))
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap("Images/heart_beat.png"))
        self.label_25.setScaledContents(False)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.page_12)
        self.label_26.setGeometry(QtCore.QRect(550, 410, 91, 71))
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap("Images/heart_beat.png"))
        self.label_26.setScaledContents(False)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.page_12)
        self.label_27.setGeometry(QtCore.QRect(640, 410, 291, 71))
        self.label_27.setText("")
        self.label_27.setPixmap(QtGui.QPixmap("Images/heart_beat.png"))
        self.label_27.setScaledContents(False)
        self.label_27.setObjectName("label_27")
        self.stackedWidget_2.addWidget(self.page_12)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_18 = QtWidgets.QLabel(self.page)
        self.label_18.setGeometry(QtCore.QRect(0, 10, 911, 91))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setWordWrap(True)
        self.label_18.setObjectName("label_18")
        self.list_recovery = QtWidgets.QListWidget(self.page)
        self.list_recovery.setGeometry(QtCore.QRect(180, 120, 531, 111))
        self.list_recovery.setObjectName("list_recovery")
        self.list_recovery.setEnabled(False)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.list_recovery.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.list_recovery.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.list_recovery.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.list_recovery.addItem(item)
        self._recovery_label = QtWidgets.QLabel(self.page)
        self._recovery_label.setGeometry(QtCore.QRect(180, 270, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self._recovery_label.setFont(font)
        self._recovery_label.setStyleSheet("color: rgb(255, 255, 255);")
        self._recovery_label.setObjectName("_recovery_label")
        self.analyse_for_recovery = QtWidgets.QPushButton(self.page)
        self.analyse_for_recovery.setGeometry(QtCore.QRect(580, 270, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.analyse_for_recovery.setFont(font)
        self.analyse_for_recovery.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.analyse_for_recovery.setObjectName("analyse_for_recovery")
        self.stackedWidget_2.addWidget(self.page)
        self.verticalLayout_6.addWidget(self.frame_3)
        self.stackedWidget.addWidget(self.analysis_page)
        self.data_page = QtWidgets.QWidget()
        self.data_page.setObjectName("data_page")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.data_page)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.stackedWidget_4 = QtWidgets.QStackedWidget(self.data_page)
        self.stackedWidget_4.setObjectName("stackedWidget_4")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.add_page_button = QtWidgets.QPushButton(self.page_4)
        self.add_page_button.setGeometry(QtCore.QRect(100, 10, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.add_page_button.setFont(font)
        self.add_page_button.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 255);")
        self.add_page_button.setObjectName("add_page_button")
        self.update_page_button = QtWidgets.QPushButton(self.page_4)
        self.update_page_button.setGeometry(QtCore.QRect(480, 10, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.update_page_button.setFont(font)
        self.update_page_button.setStyleSheet("color: rgb(255, 255, 255);")
        self.update_page_button.setObjectName("update_page_button")
        self.stackedWidget_5 = QtWidgets.QStackedWidget(self.page_4)
        self.stackedWidget_5.setGeometry(QtCore.QRect(-11, 49, 961, 591))
        self.stackedWidget_5.setObjectName("stackedWidget_5")
        self.page_14 = QtWidgets.QWidget()
        self.page_14.setObjectName("page_14")
        self.widget_2 = QtWidgets.QWidget(self.page_14)
        self.widget_2.setGeometry(QtCore.QRect(-10, 10, 991, 591))
        self.widget_2.setObjectName("widget_2")
        self.frame_5 = QtWidgets.QFrame(self.widget_2)
        self.frame_5.setGeometry(QtCore.QRect(80, 40, 201, 51))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setGeometry(QtCore.QRect(20, 10, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.patient_id_add_label = QtWidgets.QLabel(self.frame_5)
        self.patient_id_add_label.setGeometry(QtCore.QRect(150, 10, 31, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.patient_id_add_label.setFont(font)
        self.patient_id_add_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.patient_id_add_label.setObjectName("patient_id_add_label")
        self.frame_6 = QtWidgets.QFrame(self.widget_2)
        self.frame_6.setGeometry(QtCore.QRect(80, 140, 421, 31))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_28 = QtWidgets.QLabel(self.frame_6)
        self.label_28.setGeometry(QtCore.QRect(30, 0, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_28.setObjectName("label_28")
        self.name_testedit_add = QtWidgets.QTextEdit(self.frame_6)
        self.name_testedit_add.setGeometry(QtCore.QRect(130, 0, 291, 31))
        self.name_testedit_add.setObjectName("name_testedit_add")
        self.name_testedit_add.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-family: 'Georgia';\n"
"font-size: 12px;\n")
        self.frame_7 = QtWidgets.QFrame(self.widget_2)
        self.frame_7.setGeometry(QtCore.QRect(90, 300, 421, 31))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_29 = QtWidgets.QLabel(self.frame_7)
        self.label_29.setGeometry(QtCore.QRect(20, 0, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_29.setObjectName("label_29")
        self.state_combobox_add = QtWidgets.QComboBox(self.frame_7)
        self.state_combobox_add.setGeometry(QtCore.QRect(120, 1, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.state_combobox_add.setFont(font)
        self.state_combobox_add.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.state_combobox_add.setObjectName("state_combobox_add")
        self.state_combobox_add.addItem("")
        self.state_combobox_add.addItem("")
        self.state_combobox_add.addItem("")
        self.state_combobox_add.addItem("")
        self.state_combobox_add.addItem("")
        self.state_combobox_add.addItem("")
        self.state_combobox_add.addItem("")
        self.state_combobox_add.addItem("")
        self.frame_8 = QtWidgets.QFrame(self.widget_2)
        self.frame_8.setGeometry(QtCore.QRect(610, 70, 261, 121))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_30 = QtWidgets.QLabel(self.frame_8)
        self.label_30.setGeometry(QtCore.QRect(0, -10, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_30.setObjectName("label_30")
        self.active_add_radio = QtWidgets.QRadioButton(self.frame_8)
        self.active_add_radio.setGeometry(QtCore.QRect(120, 10, 95, 20))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.active_add_radio.setFont(font)
        self.active_add_radio.setStyleSheet("color: rgb(255, 255, 255);")
        self.active_add_radio.setObjectName("active_add_radio")
        self.dead_add_radio = QtWidgets.QRadioButton(self.frame_8)
        self.dead_add_radio.setGeometry(QtCore.QRect(120, 40, 95, 20))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.dead_add_radio.setFont(font)
        self.dead_add_radio.setStyleSheet("color: rgb(255, 255, 255);")
        self.dead_add_radio.setObjectName("dead_add_radio")
        self.recovered_add_radio = QtWidgets.QRadioButton(self.frame_8)
        self.recovered_add_radio.setGeometry(QtCore.QRect(120, 70, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.recovered_add_radio.setFont(font)
        self.recovered_add_radio.setStyleSheet("color: rgb(255, 255, 255);")
        self.recovered_add_radio.setObjectName("recovered_add_radio")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.widget_2)
        self.calendarWidget.setGeometry(QtCore.QRect(560, 210, 401, 241))
        self.calendarWidget.setStyleSheet("color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"background-color: rgb(85, 170, 255);")
        self.calendarWidget.setGridVisible(False)
        self.calendarWidget.setObjectName("calendarWidget")
        self.frame_9 = QtWidgets.QFrame(self.widget_2)
        self.frame_9.setGeometry(QtCore.QRect(60, 360, 451, 31))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_31 = QtWidgets.QLabel(self.frame_9)
        self.label_31.setGeometry(QtCore.QRect(10, 0, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_31.setObjectName("label_31")
        self.blood_gorup_combobox = QtWidgets.QComboBox(self.frame_9)
        self.blood_gorup_combobox.setGeometry(QtCore.QRect(150, 0, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.blood_gorup_combobox.setFont(font)
        self.blood_gorup_combobox.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.blood_gorup_combobox.setObjectName("blood_gorup_combobox")
        self.blood_gorup_combobox.addItem("")
        self.blood_gorup_combobox.addItem("")
        self.blood_gorup_combobox.addItem("")
        self.blood_gorup_combobox.addItem("")
        self.blood_gorup_combobox.addItem("")
        self.blood_gorup_combobox.addItem("")
        self.blood_gorup_combobox.addItem("")
        self.blood_gorup_combobox.addItem("")
        self.frame_10 = QtWidgets.QFrame(self.widget_2)
        self.frame_10.setGeometry(QtCore.QRect(90, 240, 421, 31))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_32 = QtWidgets.QLabel(self.frame_10)
        self.label_32.setGeometry(QtCore.QRect(20, 0, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_32.setObjectName("label_32")
        self.gender_combobox_add = QtWidgets.QComboBox(self.frame_10)
        self.gender_combobox_add.setGeometry(QtCore.QRect(120, 1, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.gender_combobox_add.setFont(font)
        self.gender_combobox_add.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.gender_combobox_add.setObjectName("gender_combobox_add")
        self.gender_combobox_add.addItem("")
        self.gender_combobox_add.addItem("")
        self.frame_11 = QtWidgets.QFrame(self.widget_2)
        self.frame_11.setGeometry(QtCore.QRect(70, 480, 421, 31))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_33 = QtWidgets.QLabel(self.frame_11)
        self.label_33.setGeometry(QtCore.QRect(0, 0, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_33.setObjectName("label_33")
        self.admit_on_add = QtWidgets.QTextEdit(self.frame_11)
        self.admit_on_add.setGeometry(QtCore.QRect(120, 0, 291, 31))
        self.admit_on_add.setObjectName("admit_on_add")
        self.admit_on_add.setStyleSheet("color: rgb(255, 255, 255);")
        self.frame_12 = QtWidgets.QFrame(self.widget_2)
        self.frame_12.setGeometry(QtCore.QRect(40, 530, 441, 31))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.discharge_add = QtWidgets.QTextEdit(self.frame_12)
        self.discharge_add.setGeometry(QtCore.QRect(150, 0, 291, 31))
        self.discharge_add.setObjectName("discharge_add")
        self.discharge_add.setStyleSheet("color: rgb(255, 255, 255);")
        self.discharge_add.setEnabled(False)
        self.discharge_add_checkbox = QtWidgets.QCheckBox(self.frame_12)
        self.discharge_add_checkbox.setGeometry(QtCore.QRect(0, 0, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.discharge_add_checkbox.setFont(font)
        self.discharge_add_checkbox.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.discharge_add_checkbox.setObjectName("discharge_add_checkbox")
        self.add_button = QtWidgets.QPushButton(self.widget_2)
        self.add_button.setGeometry(QtCore.QRect(810, 490, 131, 41))
        self.discharge_add.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.add_button.setFont(font)
        self.add_button.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.add_button.setObjectName("add_button")
        self.stackedWidget_5.addWidget(self.page_14)
        self.page_15 = QtWidgets.QWidget()
        self.page_15.setObjectName("page_15")
        self.widget_3 = QtWidgets.QWidget(self.page_15)
        self.widget_3.setGeometry(QtCore.QRect(-10, 10, 991, 591))
        self.widget_3.setObjectName("widget_3")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setGeometry(QtCore.QRect(0, 30, 991, 121))
        self.widget_4.setObjectName("widget_4")
        self.frame_13 = QtWidgets.QFrame(self.widget_4)
        self.frame_13.setGeometry(QtCore.QRect(170, 10, 211, 31))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.Id_upadate_label = QtWidgets.QTextEdit(self.frame_13)
        self.Id_upadate_label.setGeometry(QtCore.QRect(90, 0, 61, 31))
        self.Id_upadate_label.setObjectName("Id_upadate_label")
        self.Id_upadate_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-family: 'Georgia';\n"
"font-size: 12px;\n")
        self.id_radio = QtWidgets.QRadioButton(self.frame_13)
        self.id_radio.setGeometry(QtCore.QRect(20, 10, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.id_radio.setFont(font)
        self.id_radio.setStyleSheet("color: rgb(255, 255, 255);")
        self.id_radio.setObjectName("id_radio")
        self.frame_14 = QtWidgets.QFrame(self.widget_4)
        self.frame_14.setGeometry(QtCore.QRect(510, 10, 421, 31))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.name_update_text = QtWidgets.QTextEdit(self.frame_14)
        self.name_update_text.setGeometry(QtCore.QRect(130, 0, 291, 31))
        self.name_update_text.setObjectName("name_update_text")
        self.name_update_text.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-family: 'Georgia';\n"
"font-size: 12px;\n")
        self.name_update_raadio = QtWidgets.QRadioButton(self.frame_14)
        self.name_update_raadio.setGeometry(QtCore.QRect(20, 10, 95, 20))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.name_update_raadio.setFont(font)
        self.name_update_raadio.setStyleSheet("color: rgb(255, 255, 255);")
        self.name_update_raadio.setObjectName("name_update_raadio")
        self.search_button = QtWidgets.QPushButton(self.widget_4)
        self.search_button.setGeometry(QtCore.QRect(740, 70, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.search_button.setFont(font)
        self.search_button.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.search_button.setObjectName("search_button")
        self.stackedWidget_6 = QtWidgets.QStackedWidget(self.widget_3)
        self.stackedWidget_6.setGeometry(QtCore.QRect(0, 150, 1001, 441))
        self.stackedWidget_6.setObjectName("stackedWidget_6")
        self.page_16 = QtWidgets.QWidget()
        self.page_16.setObjectName("page_16")
        self.label_35 = QtWidgets.QLabel(self.page_16)
        self.label_35.setGeometry(QtCore.QRect(40, 20, 891, 20))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.list_update_results = QtWidgets.QListWidget(self.page_16)
        self.list_update_results.setGeometry(QtCore.QRect(40, 50, 891, 241))
        self.list_update_results.setObjectName("list_update_results")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.list_update_results.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.list_update_results.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.list_update_results.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.list_update_results.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.list_update_results.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.list_update_results.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.list_update_results.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.list_update_results.addItem(item)
        self.stackedWidget_6.addWidget(self.page_16)
        self.page_17 = QtWidgets.QWidget()
        self.page_17.setObjectName("page_17")
        self.frame_15 = QtWidgets.QFrame(self.page_17)
        self.frame_15.setGeometry(QtCore.QRect(90, 40, 421, 31))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label_48 = QtWidgets.QLabel(self.frame_15)
        self.label_48.setGeometry(QtCore.QRect(20, 0, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_48.setObjectName("label_48")
        self.gemder_update = QtWidgets.QComboBox(self.frame_15)
        self.gemder_update.setGeometry(QtCore.QRect(120, 1, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.gemder_update.setFont(font)
        self.gemder_update.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.gemder_update.setObjectName("gemder_update")
        self.gemder_update.addItem("")
        self.gemder_update.addItem("")
        self.gemder_update.setEnabled(False)
        self.frame_16 = QtWidgets.QFrame(self.page_17)
        self.frame_16.setGeometry(QtCore.QRect(60, 140, 451, 31))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.label_49 = QtWidgets.QLabel(self.frame_16)
        self.label_49.setGeometry(QtCore.QRect(10, 0, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_49.setFont(font)
        self.label_49.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_49.setObjectName("label_49")
        self.bloodgroup_update = QtWidgets.QComboBox(self.frame_16)
        self.bloodgroup_update.setGeometry(QtCore.QRect(150, 0, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.bloodgroup_update.setFont(font)
        self.bloodgroup_update.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.bloodgroup_update.setObjectName("bloodgroup_update")
        self.bloodgroup_update.addItem("")
        self.bloodgroup_update.addItem("")
        self.bloodgroup_update.addItem("")
        self.bloodgroup_update.addItem("")
        self.bloodgroup_update.addItem("")
        self.bloodgroup_update.addItem("")
        self.bloodgroup_update.addItem("")
        self.bloodgroup_update.addItem("")
        self.frame_17 = QtWidgets.QFrame(self.page_17)
        self.frame_17.setGeometry(QtCore.QRect(40, 270, 441, 31))
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.discharge_update = QtWidgets.QTextEdit(self.frame_17)
        self.discharge_update.setGeometry(QtCore.QRect(150, 0, 291, 31))
        self.discharge_update.setObjectName("discharge_update")
        self.discharge_update.setEnabled(False)
        self.discharge_update.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-family: 'Georgia';\n"
"font-size: 12px;\n")
        self.discharge_check = QtWidgets.QCheckBox(self.frame_17)
        self.discharge_check.setGeometry(QtCore.QRect(0, 0, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.discharge_check.setFont(font)
        self.discharge_check.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.discharge_check.setObjectName("discharge_check")
        self.frame_18 = QtWidgets.QFrame(self.page_17)
        self.frame_18.setGeometry(QtCore.QRect(90, 90, 421, 31))
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.label_50 = QtWidgets.QLabel(self.frame_18)
        self.label_50.setGeometry(QtCore.QRect(20, 0, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_50.setFont(font)
        self.label_50.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_50.setObjectName("label_50")
        self.state_update = QtWidgets.QComboBox(self.frame_18)
        self.state_update.setGeometry(QtCore.QRect(120, 1, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.state_update.setFont(font)
        self.state_update.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.state_update.setObjectName("state_update")
        self.state_update.addItem("")
        self.state_update.addItem("")
        self.state_update.addItem("")
        self.state_update.addItem("")
        self.state_update.addItem("")
        self.state_update.addItem("")
        self.state_update.addItem("")
        self.state_update.addItem("")
        self.state_update.setEnabled(False)
        self.frame_19 = QtWidgets.QFrame(self.page_17)
        self.frame_19.setGeometry(QtCore.QRect(70, 220, 421, 31))
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.label_51 = QtWidgets.QLabel(self.frame_19)
        self.label_51.setGeometry(QtCore.QRect(0, 0, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_51.setFont(font)
        self.label_51.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_51.setObjectName("label_51")
        self.admit_update = QtWidgets.QTextEdit(self.frame_19)
        self.admit_update.setGeometry(QtCore.QRect(120, 0, 291, 31))
        self.admit_update.setObjectName("admit_update")
        self.admit_update.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-family: 'Georgia';\n"
"font-size: 12px;\n")
        self.admit_update.setEnabled(False)
        self.frame_20 = QtWidgets.QFrame(self.page_17)
        self.frame_20.setGeometry(QtCore.QRect(600, 30, 261, 101))
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.label_52 = QtWidgets.QLabel(self.frame_20)
        self.label_52.setGeometry(QtCore.QRect(0, -10, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_52.setFont(font)
        self.label_52.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_52.setObjectName("label_52")
        self.active_radio = QtWidgets.QRadioButton(self.frame_20)
        self.active_radio.setGeometry(QtCore.QRect(120, 10, 95, 20))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.active_radio.setFont(font)
        self.active_radio.setStyleSheet("color: rgb(255, 255, 255);")
        self.active_radio.setObjectName("active_radio")
        self.dead_radio = QtWidgets.QRadioButton(self.frame_20)
        self.dead_radio.setGeometry(QtCore.QRect(120, 40, 95, 20))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.dead_radio.setFont(font)
        self.dead_radio.setStyleSheet("color: rgb(255, 255, 255);")
        self.dead_radio.setObjectName("dead_radio")
        self.recovered_radio = QtWidgets.QRadioButton(self.frame_20)
        self.recovered_radio.setGeometry(QtCore.QRect(120, 70, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.recovered_radio.setFont(font)
        self.recovered_radio.setStyleSheet("color: rgb(255, 255, 255);")
        self.recovered_radio.setObjectName("recovered_radio")
        self.calendarWidget_2 = QtWidgets.QCalendarWidget(self.page_17)
        self.calendarWidget_2.setGeometry(QtCore.QRect(540, 160, 401, 241))
        self.calendarWidget_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"background-color: rgb(85, 170, 255);")
        self.calendarWidget_2.setGridVisible(False)
        self.calendarWidget_2.setObjectName("calendarWidget_2")
        self.update_button = QtWidgets.QPushButton(self.page_17)
        self.update_button.setGeometry(QtCore.QRect(240, 340, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.update_button.setFont(font)
        self.update_button.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.update_button.setObjectName("update_button")
        self.stackedWidget_6.addWidget(self.page_17)
        self.stackedWidget_5.addWidget(self.page_15)
        self.stackedWidget_4.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label_40 = QtWidgets.QLabel(self.page_5)
        self.label_40.setGeometry(QtCore.QRect(340, 80, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setItalic(True)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setWordWrap(True)
        self.label_40.setObjectName("label_40")
        self.frame_22 = QtWidgets.QFrame(self.page_5)
        self.frame_22.setGeometry(QtCore.QRect(320, 210, 341, 51))
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.label_41 = QtWidgets.QLabel(self.frame_22)
        self.label_41.setGeometry(QtCore.QRect(20, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_41.setObjectName("label_41")
        self.textEdit = QtWidgets.QTextEdit(self.frame_22)
        self.textEdit.setGeometry(QtCore.QRect(130, 10, 171, 31))
        self.textEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 9pt;\n"
"border:2px solid blue;\n"
"border-color: rgb(35, 35, 35);\n"
"border-bottom-color: rgb(85, 170, 255);\n"
"")
        self.textEdit.setObjectName("textEdit")
        self.frame_23 = QtWidgets.QFrame(self.page_5)
        self.frame_23.setGeometry(QtCore.QRect(320, 300, 341, 51))
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.label_42 = QtWidgets.QLabel(self.frame_23)
        self.label_42.setGeometry(QtCore.QRect(20, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_42.setObjectName("label_42")
        self.textEdit_2 = QtWidgets.QTextEdit(self.frame_23)
        self.textEdit_2.setGeometry(QtCore.QRect(130, 10, 171, 31))
        self.textEdit_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 9pt;\n"
"border:2px solid blue;\n"
"border-color: rgb(35, 35, 35);\n"
"border-bottom-color: rgb(85, 170, 255);\n"
"")
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.page_5)
        self.pushButton.setGeometry(QtCore.QRect(500, 420, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 255);\n"
"border-radius:12px;")
        self.pushButton.setObjectName("pushButton")
        self.label_43 = QtWidgets.QLabel(self.page_5)
        self.label_43.setGeometry(QtCore.QRect(470, 20, 51, 41))
        self.label_43.setText("")
        self.label_43.setPixmap(QtGui.QPixmap("Images/cil-lock-locked.png"))
        self.label_43.setScaledContents(True)
        self.label_43.setObjectName("label_43")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_2.setGeometry(QtCore.QRect(340, 420, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);\n"
"\n"
"border-radius:12px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.stackedWidget_4.addWidget(self.page_5)
        self.stackedWidget_4.addWidget(self.page_5)
        self.verticalLayout_8.addWidget(self.stackedWidget_4)
        self.stackedWidget.addWidget(self.data_page)
        self.credits_page = QtWidgets.QWidget()
        self.credits_page.setObjectName("credits_page")
        self.label_10 = QtWidgets.QLabel(self.credits_page)
        self.label_10.setGeometry(QtCore.QRect(240, 120, 181, 171))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("Images/gsbg.jpg"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.credits_page)
        self.label_11.setGeometry(QtCore.QRect(510, 120, 181, 171))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("Images/A_logo.jpg"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.credits_page)
        self.label_12.setGeometry(QtCore.QRect(320, 10, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_16 = QtWidgets.QLabel(self.credits_page)
        self.label_16.setGeometry(QtCore.QRect(40, 120, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_19 = QtWidgets.QLabel(self.credits_page)
        self.label_19.setGeometry(QtCore.QRect(240, 300, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_34 = QtWidgets.QLabel(self.credits_page)
        self.label_34.setGeometry(QtCore.QRect(510, 300, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.label_36 = QtWidgets.QLabel(self.credits_page)
        self.label_36.setGeometry(QtCore.QRect(280, 410, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.credits_page)
        self.label_37.setGeometry(QtCore.QRect(460, 410, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.credits_page)
        self.label_38.setGeometry(QtCore.QRect(180, 480, 561, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.credits_page)
        self.label_39.setGeometry(QtCore.QRect(180, 530, 561, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.stackedWidget.addWidget(self.credits_page)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.Content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.btn_page_1.setIcon(QIcon('Images/cil-home.png'))
        self.btn_page_2.setIcon(QIcon('Images/cil-chart-line.png'))
        self.btn_page_3.setIcon(QIcon('Images/cil-code.png'))
        self.btn_page_4.setIcon(QIcon('Images/cil-credit-card.png'))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Btn_Toggle.setText(_translate("MainWindow", ""))
        self.btn_page_1.setText(_translate("MainWindow", ""))
        self.btn_page_2.setText(_translate("MainWindow", ""))
        self.btn_page_3.setText(_translate("MainWindow", ""))
        self.btn_page_4.setText(_translate("MainWindow", ""))
        self.frame.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Total Cases </span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "Total cases"))
        self.label_5.setText(_translate("MainWindow", "10.5M"))
        self.label_6.setText(_translate("MainWindow", "Recovered"))
        self.label_7.setText(_translate("MainWindow", "10.1M"))
        self.label_8.setText(_translate("MainWindow", "Death"))
        self.label_9.setText(_translate("MainWindow", "152K"))
        self.Live_cases_button.setText(_translate("MainWindow", "Live Cases"))
        self.News_labl_1.setText(_translate("MainWindow", "-> vaccine jabs to be given in 6 days"))
        self.News_label_2.setText(_translate("MainWindow", "-> over half of Delhi had covid"))
        self.News_label_3.setText(_translate("MainWindow", "-> Russian vaccine 91% accurate"))
        self.More_news_button.setText(_translate("MainWindow", "More ->"))
        self.label_2.setText(_translate("MainWindow", "Analyse for"))
        self.state_radio_button.setText(_translate("MainWindow", "State"))
        self.gender_radio_button.setText(_translate("MainWindow", "Gender"))
        self.cases_button.setText(_translate("MainWindow", "Cases"))
        self.death_radio_button.setText(_translate("MainWindow", "Death rate"))
        self.recovery_radio_button.setText(_translate("MainWindow", "Recovery rate"))
        self.Select_state_button.setText(_translate("MainWindow", "Select state "))
        self.Other_state_button.setText(_translate("MainWindow", "Other states"))
        self.rajasthan.setText(_translate("MainWindow", "Rajasthan"))
        self.maharashtra.setText(_translate("MainWindow", "Maharashtra"))
        self.madhyapradesh.setText(_translate("MainWindow", "Madhya Pradesh"))
        self.tamil_nadu.setText(_translate("MainWindow", "Tamil Nadu"))
        self.Uttar_Pradesh.setText(_translate("MainWindow", "Uttar Pradesh"))
        self.punjab.setText(_translate("MainWindow", "Punjab"))
        self.delhi.setText(_translate("MainWindow", "Delhi"))
        self.Analyse_button.setText(_translate("MainWindow", "Analyse ->"))
        self.Go_online_button.setText(_translate("MainWindow", "Go online ->"))
        self._Other_state_analyse_button.setText(_translate("MainWindow", "Analyse ->"))
        self.Go_onlline_button.setText(_translate("MainWindow", "Go Online ->"))
        self.label_13.setText(_translate("MainWindow", "Understanding the role gender is playing in the covid-19 outbreak is essential to building an effective, equitable response to the pandemic. This tracker presents the sex-disaggregated data being reported by governments."))
        self.Analyse_button__death_3.setText(_translate("MainWindow", "Analyse ->"))
        self.Analyse_button_4.setText(_translate("MainWindow", "Go Online ->"))
        self.label_15.setText(_translate("MainWindow", "Since the beginning of the pandemic, we have been tracking the COVID case & testing data and have partnered with many organizations that provide essential medical services related to COVID."))
        __sortingEnabled = self.listWidget_case.isSortingEnabled()
        self.listWidget_case.setSortingEnabled(False)
        item = self.listWidget_case.item(0)
        item.setForeground(Qt.white)
        item.setText(_translate("MainWindow", "All (Jan 2020 - Jan 2021)"))
        item = self.listWidget_case.item(1)
        item.setForeground(Qt.white)
        item.setText(_translate("MainWindow", "January 2020 - April 2020"))
        item = self.listWidget_case.item(2)
        item.setForeground(Qt.white)
        item.setText(_translate("MainWindow", "May 2020 - September 2020"))
        item = self.listWidget_case.item(3)
        item.setForeground(Qt.white)
        item.setText(_translate("MainWindow", "October 2020 - January 2021"))
        self.listWidget_case.setSortingEnabled(__sortingEnabled)
        self.list_case_label.setText(_translate("MainWindow", "All (Jan 2020 - Jan 2021)"))
        self._analyse_case_button.setText(_translate("MainWindow", "Analyse ->"))
        self.label_17.setText(_translate("MainWindow", "As is the increase in the cases over time , we see a similiar graph of the death rate , though death rate varying from just 1% in some places from 25% in some places where the sanitation was not up to the mark and lack of resources to diagnose people."))
        __sortingEnabled = self.death_list.isSortingEnabled()
        self.death_list.setSortingEnabled(False)
        item = self.death_list.item(0)
        item.setText(_translate("MainWindow", "All (Jan 2020 - Jan 2021)"))
        item = self.death_list.item(1)
        item.setText(_translate("MainWindow", "January 2020 - April 2020"))
        item = self.death_list.item(2)
        item.setText(_translate("MainWindow", "May 2020 - September 2020"))
        item = self.death_list.item(3)
        item.setText(_translate("MainWindow", "October 2020 - January 2021"))
        self.death_list.setSortingEnabled(__sortingEnabled)
        self.selected_label.setText(_translate("MainWindow", "All (Jan 2020 - Jan 2021)"))
        self.Analyse_button__death.setText(_translate("MainWindow", "Analyse ->"))
        self.label_18.setText(_translate("MainWindow", "With a high number of COVID patients recovering every day and the sustained fall in the mortality rate, India\'s steady trend of registering dipping active cases continues."))
        __sortingEnabled = self.list_recovery.isSortingEnabled()
        self.list_recovery.setSortingEnabled(False)
        item = self.list_recovery.item(0)
        item.setText(_translate("MainWindow", "All (Jan 2020 - Jan 2021)"))
        item = self.list_recovery.item(1)
        item.setText(_translate("MainWindow", "January 2020 - April 2020"))
        item = self.list_recovery.item(2)
        item.setText(_translate("MainWindow", "May 2020 - September 2020"))
        item = self.list_recovery.item(3)
        item.setText(_translate("MainWindow", "October 2020 - January 2021"))
        self.list_recovery.setSortingEnabled(__sortingEnabled)
        self._recovery_label.setText(_translate("MainWindow", "All (Jan 2020 - Jan 2021)"))
        self.analyse_for_recovery.setText(_translate("MainWindow", "Analyse ->"))
        self.add_page_button.setText(_translate("MainWindow", "Add Patient"))
        self.update_page_button.setText(_translate("MainWindow", "Update Records"))
        self.label.setText(_translate("MainWindow", "Patient_ID :-"))
        self.patient_id_add_label.setText(_translate("MainWindow", "50"))
        self.label_28.setText(_translate("MainWindow", "Name :"))
        self.label_29.setText(_translate("MainWindow", "State :"))
        self.state_combobox_add.setItemText(0, _translate("MainWindow", "Maharashtra"))
        self.state_combobox_add.setItemText(1, _translate("MainWindow", "Rajasthan"))
        self.state_combobox_add.setItemText(2, _translate("MainWindow", "Punjab"))
        self.state_combobox_add.setItemText(3, _translate("MainWindow", "Uttar Pradesh"))
        self.state_combobox_add.setItemText(4, _translate("MainWindow", "Tamil Nadu"))
        self.state_combobox_add.setItemText(5, _translate("MainWindow", "Delhi"))
        self.state_combobox_add.setItemText(6, _translate("MainWindow", "Madhya Pradesh"))
        self.state_combobox_add.setItemText(7, _translate("MainWindow", "Other States"))
        self.label_30.setText(_translate("MainWindow", "Status:"))
        self.active_add_radio.setText(_translate("MainWindow", "Active"))
        self.dead_add_radio.setText(_translate("MainWindow", "Dead"))
        self.recovered_add_radio.setText(_translate("MainWindow", "Recovered"))
        self.label_31.setText(_translate("MainWindow", "Blood Group:"))
        self.blood_gorup_combobox.setItemText(0, _translate("MainWindow", "A+ve"))
        self.blood_gorup_combobox.setItemText(1, _translate("MainWindow", "B+ve"))
        self.blood_gorup_combobox.setItemText(2, _translate("MainWindow", "A-ve"))
        self.blood_gorup_combobox.setItemText(3, _translate("MainWindow", "B-ve"))
        self.blood_gorup_combobox.setItemText(4, _translate("MainWindow", "AB+ve"))
        self.blood_gorup_combobox.setItemText(5, _translate("MainWindow", "AB-ve"))
        self.blood_gorup_combobox.setItemText(6, _translate("MainWindow", "O+ve"))
        self.blood_gorup_combobox.setItemText(7, _translate("MainWindow", "O-ve"))
        self.label_32.setText(_translate("MainWindow", "Gender:"))
        self.gender_combobox_add.setItemText(0, _translate("MainWindow", "Male"))
        self.gender_combobox_add.setItemText(1, _translate("MainWindow", "Female"))
        self.label_33.setText(_translate("MainWindow", "Admit on:"))
        self.discharge_add_checkbox.setText(_translate("MainWindow", "Discharge:"))
        self.add_button.setText(_translate("MainWindow", "Add ->"))
        self.id_radio.setText(_translate("MainWindow", "ID :"))
        self.name_update_raadio.setText(_translate("MainWindow", "Name:"))
        self.search_button.setText(_translate("MainWindow", "Search"))
        self.label_35.setText(_translate("MainWindow", "Results Found"))
        __sortingEnabled = self.list_update_results.isSortingEnabled()
        self.list_update_results.setSortingEnabled(False)
        item = self.list_update_results.item(0)
        item.setForeground(Qt.white)
        item.setText(_translate("MainWindow", ""))
        item = self.list_update_results.item(1)
        item.setForeground(Qt.white)
        item.setText(_translate("MainWindow", ""))
        item = self.list_update_results.item(2)
        item.setForeground(Qt.white)
        item.setText(_translate("MainWindow", ""))
        item = self.list_update_results.item(3)
        item.setForeground(Qt.white)
        item.setText(_translate("MainWindow", ""))
        item = self.list_update_results.item(4)
        item.setForeground(Qt.white)
        item.setText(_translate("MainWindow", ""))
        item = self.list_update_results.item(5)
        item.setForeground(Qt.white)
        item.setText(_translate("MainWindow", ""))
        item = self.list_update_results.item(6)
        item.setForeground(Qt.white)
        item.setText(_translate("MainWindow", ""))
        item = self.list_update_results.item(7)
        item.setForeground(Qt.white)
        item.setText(_translate("MainWindow", ""))
        self.list_update_results.setSortingEnabled(__sortingEnabled)
        self.label_48.setText(_translate("MainWindow", "Gender:"))
        self.gemder_update.setItemText(0, _translate("MainWindow", "Male"))
        self.gemder_update.setItemText(1, _translate("MainWindow", "Female"))
        self.label_49.setText(_translate("MainWindow", "Blood Group:"))
        self.bloodgroup_update.setItemText(0, _translate("MainWindow", "A+ve"))
        self.bloodgroup_update.setItemText(1, _translate("MainWindow", "B+ve"))
        self.bloodgroup_update.setItemText(2, _translate("MainWindow", "A-ve"))
        self.bloodgroup_update.setItemText(3, _translate("MainWindow", "B-ve"))
        self.bloodgroup_update.setItemText(4, _translate("MainWindow", "AB+ve"))
        self.bloodgroup_update.setItemText(5, _translate("MainWindow", "AB-ve"))
        self.bloodgroup_update.setItemText(6, _translate("MainWindow", "O+ve"))
        self.bloodgroup_update.setItemText(7, _translate("MainWindow", "O-ve"))
        self.bloodgroup_update.setEnabled(False)
        self.discharge_check.setText(_translate("MainWindow", "Discharge:"))
        self.label_50.setText(_translate("MainWindow", "State :"))
        self.state_update.setItemText(0, _translate("MainWindow", "Maharashtra"))
        self.state_update.setItemText(1, _translate("MainWindow", "Rajasthan"))
        self.state_update.setItemText(2, _translate("MainWindow", "Punjab"))
        self.state_update.setItemText(3, _translate("MainWindow", "Uttar Pradesh"))
        self.state_update.setItemText(4, _translate("MainWindow", "Tamil Nadu"))
        self.state_update.setItemText(5, _translate("MainWindow", "Delhi"))
        self.state_update.setItemText(6, _translate("MainWindow", "Madhya Pradesh"))
        self.state_update.setItemText(7, _translate("MainWindow", "Other States"))
        self.label_51.setText(_translate("MainWindow", "Admit on:"))
        self.label_52.setText(_translate("MainWindow", "Status:"))
        self.active_radio.setText(_translate("MainWindow", "Active"))
        self.dead_radio.setText(_translate("MainWindow", "Dead"))
        self.recovered_radio.setText(_translate("MainWindow", "Recovered"))
        self.update_button.setText(_translate("MainWindow", "Update"))
        self.label_12.setText(_translate("MainWindow", "Credits"))
        self.label_16.setText(_translate("MainWindow", "Creators:"))
        self.label_19.setText(_translate("MainWindow", "Gaurav Sharma"))
        self.label_34.setText(_translate("MainWindow", "Aditya Krishna"))
        self.label_36.setText(_translate("MainWindow", "Specials thanks:"))
        self.label_37.setText(_translate("MainWindow", "Ms. Pooja Dhingra"))
        self.label_38.setText(_translate("MainWindow", " \"      Coz Creativity is never learned or copied it\'s with you      \""))
        self.label_39.setText(_translate("MainWindow", "\"   stay creative \""))
        self.label_40.setText(_translate("MainWindow", "The content you are trying to view is hidden please login below to access it !!!"))
        self.label_41.setText(_translate("MainWindow", "Username :"))
        self.label_42.setText(_translate("MainWindow", "Password :"))
        self.pushButton.setText(_translate("MainWindow", "Login"))
        self.pushButton_2.setText(_translate("MainWindow", "Cancel"))

if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())

